## 넘파이(Numpy)

### Numpy 패키지를 임포트 해야합니다.
- Numpy 패키지의 별칭은 np라는 이름으로 임포트 하는것이 관례입니다.
- Numpy 패키지 임포트 하는 코드는 아래와 같습니다.
``` python  
import numpy as np
```

#### 1차원 배열 만들기

In [2]:
# Numpy를 임포트
#jupyter lab에서 1회만 실행하면 그 아래 코드에선 다 사용 가능합니다.
import numpy as np

In [3]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar.shape

(10,)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

#### 넘파이의 자료형

In [34]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [11]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [12]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [41]:
ar3 = np.array([_ for _ in range(3,10,3)], 'i8') #int9bytes --> 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [43]:
ar4 = np.array([_ for _ in range(2,10,2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [47]:
# 'U8' 유니코드 8글자 자료형을 명시적으로선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정되었다.
ar5 = np.array(["가나다라마","바사아", "자","차카"], 'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U8


In [48]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [49]:
x[0] + x[1]

3.0

In [61]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [51]:
x[0] + x[1]

'12'

In [52]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2068585620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2068585620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [53]:
np.log(0)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [54]:
np.exp(-np.inf)

0.0

#### 벡터화 연산

In [59]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2 * d for d in data]

In [60]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [62]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
list_samp = [_ for _ in range(3)]
print(list_samp*5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [65]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [66]:
2*a+b

array([12, 24, 36])

In [67]:
a == 2

array([False,  True, False])

In [68]:
b > 10

array([False,  True,  True])

In [69]:
(a == 2) & (b > 10)

array([False,  True, False])

#### 2차원 배열 만들기

In [26]:
c = np.array([[0,1,2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# 행의 갯수
len(c)

2

In [28]:
# 열의 갯수
len(c[0])

3

In [29]:
c.shape

(2, 3)

#### 3차원 배열 만들기

In [31]:
# 2 x 3 x 4
d = np.array([[[1,2,3,4],
               [5, 6, 7, 8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])

In [32]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [158]:
d.shape

(2, 3, 4)

#### 배열의 차원과 크기 알아내기

In [35]:
# a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [94]:
# c = np.array([0,1,2],[3,4,5])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [96]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


#### 배열의 인덱싱

In [36]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [37]:
a[2]

2

In [38]:
a[-1]

4

In [40]:
a = np.array([[0,1,2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a[0,0] # 첫번째 행의 첫번째 열

0

In [45]:
a[1,0] # 첫번째 행의 두번째 열

3

In [46]:
a[-1,-1] # 마지막 행의 마지막 열

5

#### 배열의 슬라이싱

In [138]:
a = np.array([[0,1,2,3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [139]:
np.array([_ for _ in range(8)]).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [140]:
a[0,:] # 첫번째 행 전체

array([0, 1, 2, 3])

In [141]:
a[:,1] # 두번째 혈 전체

array([1, 5])

In [142]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [143]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

#### 배열 생성

##### Numpy는 몇가지 단순한 배열을 생성하는 메서드를 제공합니다.  
  
- zeros,ones  
- zeros_likem ones_like
- empty
- arange
- linspace, logspace

In [174]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [47]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [176]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [177]:
d[0] = "abc" 
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [179]:
e = np.ones((2, 3, 4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [183]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [185]:
g = np.empty((4, 3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [186]:
np.arange(10) # 0...n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [191]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [194]:
np.logspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

#### 전치연산

In [195]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 배열의 크기변형

In [49]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [52]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [53]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [57]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [58]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [59]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### 배열연결

##### hstack

In [215]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [216]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [217]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

##### vstack

In [223]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [224]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [225]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### dstack

In [227]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [228]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [229]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [230]:
np.dstack([c1,c2]).shape

(3, 4, 2)

##### stack

In [232]:
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [233]:
c.shape

(2, 3, 4)

In [234]:
c = np.stack([c1,c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [242]:
c.shape

(3, 4, 2)

##### r_메서드

In [245]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

##### c_메서드

In [246]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

##### tile

In [247]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [248]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

#### 연습문제

##### 다음의 행렬이 주저졌을 때 1~5까지 문제를 풀어보세요.
```python  
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
```  
1. 이 행렬에서 값 7을 인덱싱한다.  
2. 이 행렬에서 값 14 을 인덱싱한다.  
3. 이 행렬에서 배열 [6,7]을 슬라이싱한다.  
4. 이 행렬에서 배열 [7,12]을 슬라이싱한다.  
5. 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱한다.

In [161]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

In [162]:
m[1,2]

7

In [163]:
m[-1,-1]

14

In [164]:
m[1,1:3]

array([6, 7])

In [170]:
m[1:,2]

array([ 7, 12])

In [168]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

##### 넘파이를 사용하여 다음과 같은 행렬을 만들어보세요.

- 실행결과:
```python
array([[10,20,30,40],
       [50,60,70,80]])
```

In [25]:
e = np.array([[10,20,30,40], [50, 60, 70, 80]])
e

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [286]:
f = np.linspace(10, 150, 15)
f2 = np.zeros((3,3))
f3 = np.ones((3,2))
f4 = np.hstack((f2,f3))
f5 = f.reshape(3,5)
f6 = np.vstack([f4,f5])
f7 = np.vstack([f6,f6])
f7

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])