## 넘파이(Numpy)

### Numpy 패키지를 임포트 해야합니다.
- Numpy 패키지의 별칭은 np라는 이름으로 임포트 하는것이 관례입니다.
- Numpy 패키지 임포트 하는 코드는 아래와 같습니다.
``` python  
import numpy as np
```

#### 배열 만들기

##### 1차원 배열 만들기

In [2]:
# Numpy를 임포트
#jupyter lab에서 1회만 실행하면 그 아래 코드에선 다 사용 가능합니다.
import numpy as np

In [3]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar.shape

(10,)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

##### 2차원 배열 만들기

In [26]:
c = np.array([[0,1,2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# 행의 갯수
len(c)

2

In [28]:
# 열의 갯수
len(c[0])

3

In [29]:
c.shape

(2, 3)

##### 3차원 배열 만들기

In [31]:
# 2 x 3 x 4
d = np.array([[[1,2,3,4],
               [5, 6, 7, 8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])

In [32]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [158]:
d.shape

(2, 3, 4)

#### 넘파이의 자료형

In [34]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [11]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [12]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [41]:
ar3 = np.array([_ for _ in range(3,10,3)], 'i8') #int9bytes --> 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [43]:
ar4 = np.array([_ for _ in range(2,10,2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [47]:
# 'U8' 유니코드 8글자 자료형을 명시적으로선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정되었다.
ar5 = np.array(["가나다라마","바사아", "자","차카"], 'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U8


In [48]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [49]:
x[0] + x[1]

3.0

In [61]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [51]:
x[0] + x[1]

'12'

In [52]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2068585620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2068585620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [53]:
np.log(0)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_11176\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [54]:
np.exp(-np.inf)

0.0

#### 벡터화 연산

- 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소애 대해 반복연산을 할 수 있습니다.  

In [59]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2 * d for d in data]

In [60]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [62]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
list_samp = [_ for _ in range(3)]
print(list_samp*5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [65]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [66]:
2*a+b

array([12, 24, 36])

In [67]:
a == 2

array([False,  True, False])

In [68]:
b > 10

array([False,  True,  True])

In [69]:
(a == 2) & (b > 10)

array([False,  True, False])

In [5]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [27]:
%%time
z = x+y

Wall time: 0 ns


In [20]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 2.99 ms


In [21]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [22]:
a == b

array([False,  True, False,  True])

In [23]:
a >= b

array([False,  True,  True,  True])

In [24]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [25]:
np.all(a == b)

False

In [26]:
np.all(a == c)

True

#### 스칼라와 벡터/행렬의 곱셈

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [30]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

#### 브로드캐스팅

In [36]:
# 배열간의 곱
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [35]:
# 스칼라
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [45]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [46]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [47]:
x + y

array([1, 2, 3, 4, 5])

In [48]:
x + 1

array([1, 2, 3, 4, 5])

#### 차원 축소 연산

##### 넘파이는 다음과 같은 차원 축소 연산 명령 혹은 메서드를 지원합니다.
- 최대/최소: min, max, argimin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

##### sum  
합산 결과를 반환합니다.  
numpy.sum() 과 ndarray()의 메서드는 동일합니다.

In [49]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [50]:
np.sum(x)

10

In [51]:
x.sum()

10

In [52]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
x.sum(axis=0) # axis=0은 행 간의 연산 결과를 구한다.

array([12, 15, 18, 21])

In [56]:
x.sum(axis=1) # axis=1은 열 간의 연산 결과를 구한다.

array([ 6, 22, 38])

##### min
해당 배열의 제일 작은 값의 결과를 반환합니다.  

In [58]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [59]:
x.min()

0

In [60]:
np.min(x)

0

In [61]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
np.min(x, axis=1)

array([[ 0,  1],
       [10, 11]])

In [63]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

##### argmin
해당 배열의 제일 작은 값의 인덱스를 반환합니다.

In [66]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [67]:
x.argmin()

0

In [68]:
np.argmin(x)

0

In [69]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [70]:
np.argmin(x, axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [72]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

##### max
해당 배열의 제일 큰 값의 결과를 반환합니다.

In [73]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [74]:
x.max()

19

In [76]:
np.max(x)

19

In [77]:
x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [78]:
np.max(x, axis=1)

array([[ 8,  9],
       [18, 19]])

In [80]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

##### argmax
해당 배열의 제일 큰 값의 인덱스를 반환합니다.

In [81]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [82]:
x.argmax()

19

In [83]:
np.argmax(x)

19

In [84]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [85]:
np.argmax(x, axis=1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [86]:
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

##### mean
평균을 구합니다.

In [357]:
x = np.array([1,2,3,1])
x.mean()

1.75

##### median
중앙값을 구합니다.

In [358]:
np.median(x)

1.5

##### np.all
배열 요소가 모두 True일 때 True를 반환합니다.
##### np.any
배열 요소가 하나라도 True면 True를 반환합니다.

In [359]:
np.all([True, True, False])

False

In [360]:
np.any([True, True, False])

True

In [362]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [363]:
((a<=b) & (b<=c)).all()

True

In [365]:
a = np.zeros((100,100), dtype=np.int64)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [367]:
np.any(a != 0)

False

In [368]:
np.all(a == a)

True

#### 정렬

##### sort

In [157]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [160]:
np.sort(a) # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [159]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [164]:
a.sort(axis=1) # a 값을 변화시킴
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

##### argsort

In [169]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [166]:
a[j]

array([12, 25, 38, 42])

In [167]:
np.sort(a)

array([12, 25, 38, 42])

#### 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

In [170]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
print(a[[0,1,2],[0,1,0]]) # a[0,0] a[1,1] a[2,0]을 인덱스로 하는 1차원 배열(shape=(3,))을 출력해준다.

[1 4 5]


In [172]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [173]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


#### 기술 통계

- 데이터의 개수
- 평균
- 분산
- 편차
- 최대/최소값
- 중앙값
- 사분위수

##### 데이터의 개수

In [369]:
x = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,
              2,5,4,15,-1,4,-7,-24,7,9,-6,23,-13])

In [371]:
len(x) #개수

26

##### 표본 평균

In [372]:
np.mean(x) #평균

4.8076923076923075

##### 표본 분산

In [373]:
np.var(x) #분산

115.23224852071006

In [374]:
np.var(x, ddof=1) # 비편향 분산. 추후 공부하게 된다.

119.84153846153846

##### 표준 편차

In [375]:
np.std(x) # 표준 편차

10.734628476137871

##### 최대값/최소값

In [377]:
np.max(x) # 최대값

23

In [378]:
np.min(x) # 최소값

-24

##### 중앙값

In [379]:
np.median(x) # 중앙값

5.0

##### 사분위수

In [380]:
np.percentile(x,0) # 최소값

-24.0

In [381]:
np.percentile(x,25) # 1사분위수

0.0

In [382]:
np.percentile(x,50) # 2사분위수

5.0

In [383]:
np.percentile(x,75) # 3사분위수

10.0

In [384]:
np.percentile(x,100) # 4사분위수

23.0

#### 난수 발생과 카운팅

##### 시드 설정하기
- 어떤 특정한 시작 숫자를 정해주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수 처럼 보이는 수열을 생성합니다.  
이런 기준이 되는 시작 숫자를 시드라고 합니다.  
- 일단 생성된 난수는 다음 번 난수 생성을 위한 시드값이 됩니다.  
따라서 시드값은 한번만정해주면 됩니다.

In [263]:
np.random.seed(0) # 인수로는 0과 같거나 큰 정수를 넣어준다.

In [264]:
np.random.rand(5) # rand 함수는 0과 1사이의 난수를 발생시키는 함수다.

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [265]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [266]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [267]:
np.random.seed(0)

In [268]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [269]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [270]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

##### 데이터의 순서 바꾸기

In [271]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
np.random.shuffle(x) # 자체 변환 함수
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

##### 데이터 샘플링

###### choice 함수는 다음과 같은 인수를 가질 수 있습니다.  
numpy.random.choice(a, size=None, replace=True, p=None)  
  
- a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
- size : 정수. 샘플 숫자.
- replace : 불리언.True이면 한번 선택한 데이터를 다시 선택 가능.
- p : 배열. 각 데이터가 선택될 수 있는 확률.

In [277]:
np.random.choice(5, 5, replace=False) # shuffle 명령과 같다.

array([4, 2, 3, 1, 0])

In [278]:
np.random.choice(5, 3, replace=False) # 3개만 선택

array([0, 3, 2])

In [279]:
np.random.choice(5,10) # 반복해서 10개 선택

array([3, 2, 3, 0, 3, 4, 1, 2, 4, 3])

In [282]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 0, 2, 2, 2, 2, 2, 3])

##### 난수 생성  
- rand : 0부터 1사이의 균일 분포
- randn : 표준 정규 분포
- randint : 균일 분포의 정수 난수

###### rand

In [283]:
np.random.rand(10)

array([0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805,
       0.09394051, 0.5759465 , 0.9292962 , 0.31856895, 0.66741038])

In [284]:
np.random.rand(3,5)

array([[0.13179786, 0.7163272 , 0.28940609, 0.18319136, 0.58651293],
       [0.02010755, 0.82894003, 0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314, 0.57615733, 0.59204193]])

###### randn
- 기댓값이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수를 생성합니다.

In [285]:
np.random.randn(10)

array([-1.44553558,  0.37716061, -0.07055723,  0.60415971,  0.472149  ,
        0.81991729,  0.90751962, -0.58582287,  0.93755884, -0.25460809])

In [286]:
np.random.randn(3,5)

array([[ 9.73598712e-01,  2.07282772e-01,  1.09964197e+00,
         9.39896981e-01,  6.06389001e-01],
       [ 1.76084071e-03, -9.90160143e-01,  1.87239408e+00,
        -2.41073590e-01,  5.33449070e-02],
       [ 1.03081595e+00, -1.27698899e+00,  8.37719765e-01,
        -1.49011141e+00, -1.07021500e+00]])

###### randint
- numpy.random.randint(low, high=None, size=None)
- 만약 high를 입력하지 않으면 0과 low 사이의 숫자를

In [287]:
np.random.randint(10, size=10)

array([6, 9, 1, 6, 8, 8, 3, 2, 3, 6])

In [288]:
np.random.randint(10, 20, size=10)

array([13, 16, 15, 17, 10, 18, 14, 16, 15, 18])

In [291]:
np.random.randint(10, 20, size=(3, 5))

array([[18, 11, 15, 18, 14],
       [10, 12, 15, 15, 10],
       [18, 11, 11, 10, 13]])

##### 정수 데이터 카운팅

In [351]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [354]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [355]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [356]:
count

array([2, 2, 1], dtype=int64)

In [353]:
np.bincount([1,1,2,2,2,3],minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

#### 배열의 차원과 크기 알아내기

In [35]:
# a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [94]:
# c = np.array([0,1,2],[3,4,5])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [96]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


#### 배열의 인덱싱

In [36]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [37]:
a[2]

2

In [38]:
a[-1]

4

In [40]:
a = np.array([[0,1,2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a[0,0] # 첫번째 행의 첫번째 열

0

In [45]:
a[1,0] # 첫번째 행의 두번째 열

3

In [46]:
a[-1,-1] # 마지막 행의 마지막 열

5

#### 배열의 슬라이싱

In [138]:
a = np.array([[0,1,2,3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [139]:
np.array([_ for _ in range(8)]).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [140]:
a[0,:] # 첫번째 행 전체

array([0, 1, 2, 3])

In [141]:
a[:,1] # 두번째 혈 전체

array([1, 5])

In [142]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [143]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

#### 배열 생성

##### Numpy는 몇가지 단순한 배열을 생성하는 메서드를 제공합니다.  
  
- zeros,ones  
- zeros_likem ones_like
- empty
- arange
- linspace, logspace

In [174]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [47]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [176]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [177]:
d[0] = "abc" 
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [179]:
e = np.ones((2, 3, 4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [183]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [185]:
g = np.empty((4, 3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [186]:
np.arange(10) # 0...n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [191]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [194]:
np.logspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

#### 전치연산

In [195]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 배열의 크기변형

In [49]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [52]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [53]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [57]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [58]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [59]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### 배열연결

##### hstack

In [215]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [216]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [217]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

##### vstack

In [223]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [224]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [225]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### dstack

In [227]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [228]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [229]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [230]:
np.dstack([c1,c2]).shape

(3, 4, 2)

##### stack

In [232]:
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [233]:
c.shape

(2, 3, 4)

In [234]:
c = np.stack([c1,c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [242]:
c.shape

(3, 4, 2)

##### r_메서드

In [245]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

##### c_메서드

In [246]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

##### tile

In [247]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [248]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

#### 연습문제

##### 다음의 행렬이 주저졌을 때 1~5까지 문제를 풀어보세요.
```python  
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
```  
1. 이 행렬에서 값 7을 인덱싱한다.  
2. 이 행렬에서 값 14 을 인덱싱한다.  
3. 이 행렬에서 배열 [6,7]을 슬라이싱한다.  
4. 이 행렬에서 배열 [7,12]을 슬라이싱한다.  
5. 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱한다.

In [161]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

In [162]:
m[1,2]

7

In [163]:
m[-1,-1]

14

In [164]:
m[1,1:3]

array([6, 7])

In [170]:
m[1:,2]

array([ 7, 12])

In [168]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

##### 넘파이를 사용하여 다음과 같은 행렬을 만들어보세요.

- 실행결과:
```python
array([[10,20,30,40],
       [50,60,70,80]])
```

In [25]:
e = np.array([[10,20,30,40], [50, 60, 70, 80]])
e

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

##### 앞서 배운 내용을 활용해서 다음과 동일한 배열을 만들어 보세요.
```python
array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])
```

In [286]:
f = np.linspace(10, 150, 15)
f2 = np.zeros((3,3))
f3 = np.ones((3,2))
f4 = np.hstack((f2,f3))
f5 = f.reshape(3,5)
f6 = np.vstack([f4,f5])
f7 = np.vstack([f6,f6])
f7

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

##### 실수로 이루어진 5x6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [151]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [325]:
practice.max()

9.0

In [153]:
practice.sum(axis=0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [154]:
practice.max(axis=0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [155]:
practice.mean(axis=1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [174]:
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

#####  다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어성적, 세번째 행에 수학 성적을 적은 배열이다.  
영어 성적을 기준으로 각 열(column)을 재정렬해보세요.  
```python
score = np.array([[1,2,3,4],
                  [46,99,100,71],
                  [81,59,90,100]])
```

In [237]:
score = np.array([[1,2,3,4],
                  [46,99,100,71],
                  [81,59,90,100]])
j = np.argsort(score[1,:])
print(score[:,j])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


##### 동전을 100번 던진 결과를 넘파이에 난수를 발생시켜서 시뮬레이션해보려 합니다.  
앞면을 숫자 1,  뒷면을 숫자 0으로 가정하고 난수를발생시켜보세요. 이떄 앞면이 나올 확률을 구하는 프로그램을 구현해보세요.  
(seed는 0으로 합니다.)

In [339]:
np.random.seed(0)
coin_result = np.random.choice(2,100)
coin_result.sum()/len(coin_result)

0.56

##### 주사위는 1부터 6까지의 숫자를 가집니다.  
이 주사위를 100번 던져서 나오는 숫자를 넘파이 난수를 발생시켜서 시뮬레이션하고 나오는 숫자의 평균을 구해보세요.  
(seed는 0으로 설정합니다.)

In [350]:
np.random.seed(0)
dice_result = np.random.randint(1,7, size=100)
np.mean(dice_result)

3.42